### ISSUE TITLE
Can't use Google Workspace (formerly as google suite) account

### ISSUE THREAD

**Issue by YTRemRem** [YTVanced/VancedMicroG#142]
Can't use Google Workspace (formerly as google suit) account
When using a google workspace account, it will shows as can't connect and keep telling you to retry

**Comment by SubhashBose** [comment]
Same issue. This keeps on happening after every few days, and then it starts woking by itself. Vanced or microg is not stable with Google workspace / GSuit accounts.

**Comment by SubhashBose** [comment]
Hi Milind, 

thanks for this information. 

Actually, earlier I tried to find this option in the Gsuit admin console, I couldn't find it at that time. Today, after your reply, I went through google help articles and finally found it, it didn't even show up in the search in the admin console settings. It seems hidden pretty deep. Admin console has become quite confusing recently and options differ a lot across editions.

I will put the instruction here, in case someone else is also having difficulty in finding it.
To find this setting - Go to "Devices", then on the left navigation bar, go to "Settings> Universal settings", then click the "General" section, then edit "Mobile management" setting and change it to "Turn off mobile management (Unmanaged)". 

However, at this moment I can not verify if changing this setting actually solves the issue, because currently, Vanced is again working normally (withing this tweak). I just hope the issue doesn't reappear again.

**Comment by Shados** [comment]
@SubhashBose I can confirm that fixes the issue! Was having the problem, made that config change, and the account connected just fine on the next refresh. Thanks a lot.

**Comment by ObscureScience** [comment]
I found this issue as I've been unable to use my account to log into Aurora Store. However, the action described above only seems accessable to managed accounts, not personal ones. Is someone actually able to login to Aurora Store with a personal account?

Sorry for discussing a different product, but the problem with the method described is relevent for both
