### ISSUE TITLE
A option to hide VancedMicroG from the launcher.

### ISSUE THREAD

**Issue by PranavBhattarai** [YTVanced/VancedMicroG#76]
There are users who might don't want to see or use the VanceMircroG app at all. Once the user signs into his/her YouTube account, VacedMicroG is barely touched/used. 

I think it's a good idea to provide an in-app option to toggle which hides VancedMicroG from showing itself in the launcher _if it's possible_. 

Let the user decide.

**Comment by matke-84** [comment]
I agree with @PranavBhattarai

**Comment by michael1900** [comment]
I don't agree with both. This change that you two want will BREAK the possibility of disable battery optimizations on ALL Huawei phones. 
Again, so not please!

**Comment by PranavBhattarai** [comment]
@michael1900 Huawei user won't have to enable the hide option which I am speaking of. It won't break battery optimization.

**Comment by vangyyy** [comment]
I fully agree with @PranavBhattarai. I was using Vanced for a long time and for some reason after I updated recently, the icon started showing.

Once you install it, you will never interact with it again. There should at least be an option to hide it, since not every launcher supports hiding icons and its taking space for nothing.

**Comment by michael1900** [comment]
LOL but what is the problem to see an icon? Bah...

**Comment by KevinX8** [comment]
https://www.reddit.com/r/androiddev/comments/de9968/hiding_an_app_icon_is_no_longer_possible_in/ it is not possible to add such an option on android 10 and higher so there is not much point adding a toggle that will only work for half of our users and will continue to work on less and less devices as people update, the icon was added to allow battery optimisations to be disabled on Huawei devices which we saw as more important than a cosmetic icon being hidden. We also see no reason to maintain two separate builds of microg just for the reason of an easily hidden icon.

**Comment by Oizaro** [comment]
> LOL but what is the problem to see an icon? Bah...

In truth? Is annoying, because microg settings are already accessible from vanced. it is simply redundant.

**Comment by Oizaro** [comment]
...in every case this icon could be hidden from launcher settings (in my case Samsung give me this possibility).

**Comment by vangyyy** [comment]
Why is it that the vanilla microg does not require launcher icon then (I'm genuinely curious)? If what @Oizaro is saying is true and same settings are exposed inside vanced app, them I really don't see the point of having launcher icon.

**Comment by Oizaro** [comment]
> Why is it that the vanilla microg does not require launcher icon then (I'm genuinely curious)? If what @Oizaro is saying is true and same settings are exposed inside vanced app, them I really don't see the point of having launcher icon.

Also vanilla microg have this icon. We just remove it in past cause the already explained reason (redundancy). Unfortunately in the last period Huawei users started complaining   because EMUI doesn't show MicroG inside battery optimization list, so we restore it because there wasn't any alternative to solve the problem.

The rest of story is related to Google choice, which avoided the possibility of hiding the icon at will such a protection against malware.

**Comment by ToastcodeDev** [comment]
It is true it is a bit annoying to have the icon there, before it only had a plugin-like structure and boy did I like it.

**Comment by Chilace** [comment]
If I hide the icon from the launcher, then the battery optimization state will not persist between reboots and the notification from Vanced microG will always be on.
Redmi Note 7 MIUI 12.5 by xiaomi.eu 21.3.17 beta.
